LEARNING_PATH="Commerce"
COURSES=(
  --foundations-of-commerce
  --commerce-users-and-accounts
  --commerce-product-management
  --commerce-inventory-management
  --commerce-pricing
  --commerce-order-management
  --commerce-storefronts
)
