LEARNING_PATH="Content Manager"
COURSES=(
  --publishing-tool-and-content-lifecycle
  --pages-navigation
  --search-engine-optimization
  --content-search
  --personalized-experiences
  --classic-cms
  --content-management-system
)
